---
- name: Install iptables rules
  copy: src=spigot.rules dest=/etc/iptables.d/spigot.rules owner=root group=root mode=0640
  notify: iptables

- name: Create the bungeecord directory
  file: path={{ prefixPath }}/bungeecord state=directory owner=minecraft group=minecraft mode=0755

- name: Create the build root
  file: path={{ prefixPath }}/build/ state=directory owner=minecraft group=minecraft mode=0755

- name: Create the local bin directory
  file: path={{ prefixPath }}/bin/ state=directory owner=minecraft group=minecraft mode=0755

- name: Obtain BungeeCord binary
  get_url: url={{ BungeeCord_url }} dest={{ prefixPath }}/bin/BungeeCord.jar owner=minecraft group=minecraft mode=0644

- name: Create the BungeeCord folder
  file: path={{ prefixPath }}/bungeeCord state=directory owner=minecraft group=minecraft mode=0755

- name: Link BungeeCord binary
  file: src={{ prefixPath }}/bin/BungeeCord.jar dest={{ prefixPath }}/bungeeCord/bungeeCord.jar state=link owner=minecraft group=minecraft

- name: Retrieve BungeeRelay Source
  git: clone=yes depth=1 force=yes dest={{ prefixPath }}/build/BungeeRelay repo=https://github.com/collegiumv/BungeeRelay

- name: Attempt to build BungeeRelay
  command: mvn package chdir={{ prefixPath }}/build/BungeeRelay creates={{ prefixPath }}/build/BungeeRelay/target/BungeeRelay.jar

- name: Link BungeeRelay to bin
  file: src={{ prefixPath }}/build/BungeeRelay/target/BungeeRelay.jar dest={{ prefixPath }}/bin/BungeeRelay.jar state=link

- name: Configure Bungee
  template: src=bungeeConfig.yml dest={{ prefixPath }}/bungeeCord/config.yml owner=minecraft group=minecraft mode=0644

- name: Create BungeeCord plugins folder
  file: path={{ prefixPath }}/bungeeCord/plugins state=directory owner=minecraft group=minecraft mode=0755

- name: Create BungeeRelay data folder
  file: path={{ prefixPath }}/bungeeCord/plugins/BungeeRelay state=directory owner=minecraft group=minecraft mode=0755

- name: Link BungeeRelay to BungeeCord plugins
  file: src={{ prefixPath }}/bin/BungeeRelay.jar dest={{ prefixPath }}/bungeeCord/plugins/BungeeRelay.jar state=link

- name: Load BungeeRelay config data
  include_vars: irc.yml

- name: Configure BungeeRelay
  template: src=bungeerelay.yml dest={{ prefixPath }}/bungeeCord/plugins/BungeeRelay/config.yml owner=root group=minecraft mode=0640

- name: BungeeCord start script
  template: src=bungeeStart.sh dest={{ prefixPath }}/bungeeCord/start.sh owner=minecraft group=minecraft mode=0755

- name: Create the runit service directory
  file: path=/etc/sv/spigot-cluster state=directory owner=root group=root mode=0755
  when: ansible_lsb.id == "Void"

- name: Copy the runit service file
  template: src=run.j2 dest=/etc/sv/spigot-cluster/run owner=root group=root mode=0755
  when: ansible_lsb.id == "Void"

- name: Enable the runit service
  file: src=/etc/sv/spigot-cluster dest=/var/service/spigot-cluster state=link
  when: ansible_lsb.id == "Void"
